[build]
  # This command tells Netlify to go into your project folder and then run the build
  command = "cd safemode-ai-blog && pnpm build"

  # This tells Netlify where to find the finished site relative to your repository root
  publish = "safemode-ai-blog/out"

[build.environment]
  NODE_VERSION = "20"
