# Netlify configuration file for a Next.js project using pnpm

[build]
  # Directory to change to before starting a build.
  # This is the folder that contains your package.json.
  base = "safemode-ai-blog"

  # The command to build your site.
  # We specify 'pnpm build' because the project uses pnpm.
  command = "pnpm build"

  # The directory that contains the deploy-ready HTML files and assets.
  # For Next.js, this is the .next folder.
  publish = ".next"

[build.environment]
  # Specify a modern Node.js version to ensure compatibility.
  NODE_VERSION = "20"
