# The official Netlify configuration for a standard Next.js application.
# This handles dynamic pages, static pages, and everything else correctly.

[build]
  # This tells Netlify where your Next.js project is located.
  base = "safemode-ai-blog"

  # This is the standard command to build the site.
  command = "pnpm build"

  # For a standard Next.js build, the output directory is always ".next".
  publish = ".next"

# This official Netlify plugin is the key to making everything work.
# It intelligently handles your Next.js site's output.
[[plugins]]
  package = "@netlify/plugin-nextjs"
