[build]
  # This tells Netlify where your Next.js project is located.
  base = "safemode-ai-blog"

  # This new command forces a clean install and then runs the build.
  # It will delete old node_modules, install fresh from your pnpm-lock.yaml,
  # and then build your Next.js site.
  command = "rm -rf node_modules && pnpm install --frozen-lockfile && pnpm build"

  # The output directory is correct.
  publish = ".next"

# This plugin is correct and necessary.
[[plugins]]
  package = "@netlify/plugin-nextjs"